### ISSUE TITLE
issues running

### ISSUE THREAD

**Issue by MRX-8** [devlancer412/cryptitan#1]
i used ubuntu and windows but can't run. please help

**Comment by devlancer412** [comment]
do you know what is it?

**Comment by MRX-8** [comment]
yes. bro please i'm begging you please tell me how to install it properly. i've checked everywhere on how to do it and for days now i've not had any progress

**Comment by MRX-8** [comment]
bro please help my life. please bro

**Comment by devlancer412** [comment]
I bought this template from online template shop. Can't sure how did I run this code. I can remember there was a serialize key. so can't use app without that key

**Comment by MRX-8** [comment]
But how did you do it for it to run. Bro please help me out I'm begging you. Please how do I run it. Bro please help my life
